spring:
  profiles:
    active: local
  application:
    name: page-pilot-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/page_pilot
    username: root
    password: 123456
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600 # 单位：秒，这里是一小时
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.aih.pagepilot.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn